### PR TITLE
Support For Resume Gateway URL

### PR DESCRIPTION
**Pull request by infinitytmbots**
Added Support for Resume Gateway URL. 
Although [this pull request](https://github.com/spec-tacles/go/pull/9) needs to be closed prior to approving this.

### CODE REVIEW

**Comment by infinitytmbots** [comment]
Resolves #16

**Comment by appellation** [comment]
spec-tacles/go#9 is merged, so this probably just needs a dependency update to pass CI

**Comment by infinitytmbots** [comment]
I've updated the dependency

**Comment by infinitytmbots** [comment]
Its ready to go

**Pull request merged**
